version: '2'
services:
  db:
    image: postgres
    ports:
    - "5431:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "javaurl"
  website:
    depends_on:
    - 'db'
    build: .
    ports:
    - '80:8080'